### Testing store a user
POST http://localhost:1996/api/users
Content-Type: application/json

{
  "args": {
    "lastName": "Lzq",
    "name": "Anthony"
  }
}

### Testing getAll users
GET http://localhost:1996/api/users

### Testing deleteAll users
DELETE http://localhost:1996/api/users

### Testing getOne user
GET http://localhost:1996/api/user/625cd71331fecdf2082b0269

### Testing update user
PATCH http://localhost:1996/api/user/625cd71331fecdf2082b0269
Content-Type: application/json

{
  "args": {
    "name": "Anthony",
    "lastName": "Lzq"
  }
}

### Testing delete user
DELETE http://localhost:1996/api/user/625cd71331fecdf2082b0269
