FROM node:18-alpine
<% if (managerName === 'pnpm') { %>
RUN corepack enable
<% } %>
WORKDIR /app

COPY . ./

RUN <%- managerName === 'yarn' ? 'yarn' : managerName === 'npm' ? 'npm' : 'pnpm' %> i

CMD [ "<%- managerName %>", "start" ]