name: Tests - example/fastify-mongo-graphql

on: [push]

jobs:
  test:
    environment: Test
    name: Testing Simba.js API
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Node.js dependencies
        run: pnpm i --frozen-lockfile

      - name: Run test
        run: pnpm i test:ci
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: ci
