name: Tests - example/express-graphql

on: [push]

jobs:
  test:
    name: Testing Simba.js API
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Node.js dependencies
        run: npm ci

      - name: Revert changes into the package-lock.json file
        run: git checkout -- package-lock.json

      - name: Run test
        run: npm run test:ci
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          NODE_ENV: ci
