name: Tests-mongo

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  test:
    name: Tests for Simba APIs with mongo
    environment: Test-mongo
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Test APIs
        run: npm run test:ci:mongo
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          NODE_ENV: ci
          PORT: 1997
